DIALOG ESPNHelpMenu
{
	NAME HELP_DIALOG; CENTER_V; SCALE_H;
	GROUP IDC_STATIC
	{
		ROWS 2;
		ALIGN_TOP; SCALE_H;
		BITMAPBUTTON HELP_IMAGE { BORDER; ICONID1 1037183; }
		//BUTTON CLOSE { NAME CLOSE; ALIGN_RIGHT; SIZE 100, 30; }
	}
}